config/routes.rb
Rails.application.routes.draw do

#Ticket
  get 'ticket/addToTicket' => 'ticket#addToTicket'
  get 'ticket/checkTicketStatus' => 'ticket#checkTicketStatus'
  get 'ticket/calcTotal' => 'ticket#calcTotal'
  get 'ticket/advance_ticket' => 'ticket#advance_ticket'
  get 'ticket/update_gratuity' => 'ticket#update_gratuity'
  get "ticket/compticket" => 'ticket#compticket'
  get 'ticket/kids' => 'ticket#kids'

#Ingredients
  get 'ingredients/update_status' => 'ingredients#update_status'
  
#Order_items
  get 'order_items/show' => 'order_items#show' 
  get 'order_items/addToTicket' => 'order_items#orderToTicket'
  get 'order_items/updateStatus' => 'order_items#updateStatus'
  get 'order_items/remove_item'=> 'order_items#remove_item'
  get 'order_items/comp' => 'order_items#comp'

#Users
  get 'manager' => 'user#manager'
  get 'manager/reports' => 'user#reports'
  get 'tableview' => 'user#tableview'
  get 'guest' => 'user#guest'
  get 'kitchen' => 'user#kitchen'
  get 'waiter' => 'user#waiter'
  get 'waiter/refills' => 'user#waiter_refills'
  get 'waiter/help' => 'user#waiter_help'
  get 'table/reset_status' => 'user#reset_status'
  get 'guest/pay' => 'user#pay'
  get 'login' => 'user#login'
  get 'guest/confirm_order' => 'user#confirm_order'
  get 'guest/refill' => 'user#refill'

 #Guestaccount
  get 'signup' => 'guestaccounts#new'
  resources :guestaccounts
  
  get '/guestlogin' => 'sessions#new'
  post 'guestlogin' => 'sessions#create'
  delete 'guestlogout' => 'sessions#destroy'

  get 'guest/pay_w_credit' => 'guest#pay_w_credit'
  get 'guest/submit_payment' => 'guest#submit_payment'
  get 'guest/thank_you' => 'guest#thank_you'

  get 'user/waiter_table_gateway' => 'user#waiter_table_gateway'

  get 'menu_item/change_availability' => 'menu_item#change_availability'
  
  root "user#login"
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def manager
  end

  #Generates reports based on which report is selected
  def reports

    # Revenue report initialization
    if params[:view] == 'revenue'
      @subtotal = 0
      @total = 0
      @tax = 0
      @gratuity = 0
      @birthdays = 0
      @points = 0
      @coupons = 0
      ticket = Ticket.all
      #Sum values from all tickets
      ticket.each do |bill|
        @subtotal += bill.subtotal unless bill.subtotal.nil? 
        @tax += bill.tax unless bill.tax.nil?
        @gratuity += bill.gratuity unless bill.gratuity.nil?
        @total += bill.total unless bill.total.nil?
        @birthdays += 1 if bill.birthday
        @points += 1 if bill.points
        @coupons += 1 if bill.coupon
      end
      #Generate list and attach values
      @items_sold = []
      @menuitems = Menuitem.all
      @menuitems.each do |item|
        @items_sold << OrderItem.where(item:item.id).count
      end 
    # Top seller report  
    elsif params[:view] == 'top sellers'
      @best_sellers = []
      ['Appetizers','Entrees','Desserts','Drinks'].each do |category|
        #initialize values to zero
        top_sell_id = 0
        top_sell_count = 0

        second_sell_id = 0
        second_sell_count = 0

        third_sell_id = 0
        third_sell_count = 0

        menuitems = Menuitem.where(category:category)
        #total and organize top 3 of each catagory
        menuitems.each do |item|
          items_sold = OrderItem.where(item:item.id).count
          if items_sold > top_sell_count
            third_sell_id = second_sell_id
            third_sell_count = second_sell_count
            
            second_sell_id = top_sell_id
            second_sell_count = top_sell_count
  
            top_sell_id = item.id
            top_sell_count = items_sold
  
          elsif items_sold > second_sell_count
            third_sell_id = second_sell_id
            third_sell_count = second_sell_count
              
            second_sell_id = item.id
            second_sell_count = items_sold
  
          elsif items_sold > third_sell_count
            third_sell_id = item.id
            third_sell_count = items_sold
          end
        end
        
        #print top sellers
        @best_sellers << Menuitem.where(id:top_sell_id).first
        @best_sellers << Menuitem.where(id:second_sell_id).first
        @best_sellers << Menuitem.where(id:third_sell_id).first
     end
     #Comp item report
    elsif params[:view] == 'compitem'
      orderitems = OrderItem.where(compitem:true)
      @compitems = []
      @menuitem = []
      orderitems.each do |order|
        @compitems << Compitem.where(id:order.compitem_id).first
        @menuitem << Menuitem.where(id:order.item).first.name
      end 
      tickets = Ticket.where("compticket_id IS NOT ?", nil)
      tickets.each do |ticket|
        @compitems << Compticket.where(id:ticket.compticket_id).first
        @menuitem << "Ticket from Table#{ticket.table}"
      end 
    end
  end

  def tableview
  end

  def guest
  end

  def waiter
  end

  #Generates list of drinks that need refill for waiter tables view
  def waiter_refills
    table = Table.find_by(username: "Table#{params[:table]}")
    table.update(refills: params[:drink])    
    redirect_to guest_path
  end

  #Generates help message for waiter if help or pay cash button pressed
  def waiter_help 
	table = Table.find_by(username: "Table#{params[:table]}")
	table.update(help: true)
    if params[:paying_cash]
      redirect_to guest_confirm_order_path, :paying_cash => true
    else
  	 redirect_to guest_path
    end
  end

  # Allows waiter/manager to reset status of table
  # Clears refill and help requests
  def reset_status
	table = Table.find_by(username: "Table#{params[:table]}")
	table.update(refills: nil, help: false)
	redirect_to waiter_path
  end

  def kitchen
  end

  def pay
  end

  #Initial login
  #Check users and Table database for logins
  def login
    begin params[:username].empty?
      user = User.find_by(username: params[:username])
      if user.nil?#if it is nil then it found nothing in User database
        user = Table.find_by(username: params[:username])
        if user.nil? #if user is nill it wasn't found in Table database
          flash[:alert] = "Incorrect credientials1!"
        else#Else Table was found
          table_id = user.username.byteslice(5,2)
          session[:table_id] = table_id
          session[:username] = user.username
          session[:accesslevel] = 1
          redirect_to guest_path
        end
      else#Else manager was found
        if user.password == params[:password]
          if user.accesslevel == 4
            session[:table_id] = 0
            session[:username] = user.username
            session[:accesslevel] = 4
            redirect_to manager_path
            #Server was found
          elsif user.accesslevel == 3
            session[:table_id] = 0
            session[:username] = user.username
            session[:accesslevel] = 3
            redirect_to waiter_path
            #Kitchen was found
          elsif user.accesslevel == 2
            session[:table_id] = 0
            session[:username] = user.username
            session[:accesslevel] = 2
            redirect_to kitchen_path
          end
        else
          flash[:alert] = "Incorrect credientials123!"
        end
      end
    rescue
      flash.now[:alert] = "Username can't be blank"
    end 
  end

  #allows server/manager to emulate table for customer
  def waiter_table_gateway
    puts(params[:table_id])
    session[:table_id] = params[:table_id]
    redirect_to guest_confirm_order_path
  end

  #Calculates total for payment and notification
  #Before and after ticket is sent to kitchen or ready
  # to be cashed out
  def confirm_order
    @check = Ticket.where(table: session[:table_id]).last
    if @check.nil?
      puts("ticket not created yet!")
      return
    end
    @items = OrderItem.where(:ticket_id => @check.id)
    @check.update(:subtotal => 0)
	 # Add item totals
	 comp = 0
    @items.each do |orderItem|
      menu_item = Menuitem.find_by(id: orderItem.item)
      @check.update(:subtotal => (@check.subtotal + menu_item.price))
		unless orderItem.compitem.nil?
			comp = comp + orderItem.compitem.amount
		end
    end

	 
	 # check reward points
	 if current_guestaccount
		 # check points
		 if current_guestaccount.points > 4
			 @check.update(:subtotal => (@check.subtotal - 10.00))
			 @check.update(:points => true)
		 end
		 # check birthday
		 if (current_guestaccount.birthday.month == Time.now.month &&
			  current_guestaccount.birthday.day == Time.now.day)
			 @check.update(:birthday => true)
		 end
	 end
	 
	 # check birthday discount
	 if @check.birthday
		 @check.update(:subtotal => (@check.subtotal - 10.00))
	 end
	 
	 # check coupon
	 if @check.coupon
		 @check.update(:subtotal => (@check.subtotal - 10.00))
	 end

	 #adjust subtotal for comp
	 @check.update(:subtotal => (@check.subtotal - comp))
   unless @check.compticket.nil? 
   @check.update(:subtotal => (@check.subtotal - @check.compticket.amount))
   end

	 # subtotal cannot be negative
	 if @check.subtotal < 0
		 @check.update(:subtotal => 0)
	 end

	 # calculate tax
	 @check.update(:tax => (@check.subtotal * 0.0825))
	 
	 unless @check.gratuity.nil?
		 @check.update(:total => (@check.subtotal + @check.tax + @check.gratuity))
	 else
	 @check.update(:total => (@check.subtotal + @check.tax))
	 end
  end

  #Sends refill message to table view for server/managers to see
  def refill
    check = Ticket.where(table: session[:table_id]).last
	 unless check.nil?
		@items = OrderItem.where(:ticket_id => check.id)
	 end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/_games.html.erb
<ul class = "small-block-grid-4">

<li>
<a href="/games/mario/main.html"> 
  <img src="/games/images/mario.png" alt="Infinite Mario" style="width:200px;height:200px;border:0">
</a>
<h5>Mario</h5>
</li>


<li><a href="/games/alienInvasion/index.html">
  <img src="/games/images/alienInvasion.png" alt="Alien Invasion" style="width:200px;height:200px;border:0">
</a>
<h5>Alien Invasion</h5>
</li>


<li><a href="/games/clumsyBird/index.html">
  <img src="/games/images/clumsyBird.png" alt="Clumsy Bird" style="width:200px;height:200px;border:0">
</a>
<h5>Clumsy Bird</h5>
</li>

<li><a href="/games/2048/index.html">
  <img src="/games/images/2048.png" alt="2048" style="width:200px;height:200px;border:0">
</a>
<h5>2048</h5>
</li>

</ul>

app/views/user/_kids_menu.html.erb
<% drinks = Menuitem.where(category:'kids drink') %>
<% entrees = Menuitem.where(category:'kids entree') %>
<% sides = Menuitem.where(category:'kids side') %>

<div class='large-6 columns large-centered'>
  <%= form_tag ticket_kids_path(params:params), method:'get' do %>
    <fieldset>
      <legend>Choose 1 Drink</legend>
      <%= collection_select :drink, :name, drinks, :name, :name %>
    </fieldset>
  
    <fieldset>
      <legend>Choose 1 Entree</legend>
      <%= collection_select :entree, :name, entrees, :name, :name %>
    </fieldset>
  
    <fieldset>
      <legend>Choose 1 Side</legend>
      <%= collection_select :side, :name, sides, :name, :name %>
    </fieldset>
    <%= submit_tag 'Add to order', class:'button radius success' %>
  <% end %>
</div>

app/views/user/_menu.html.erb
<% if ["Drinks", "Appetizers", "Entrees", "Desserts"].include? params[:view] %>
  <p style="font-size:48px">
    <center><strong>Which would you like?</strong></center>
  </p>
  <div>
    <% menuitems = Menuitem.all %>
    <ul class="small-block-grid-3">
      <% menuitems.each do |item|%>
        <% if item.category == params[:view] && item.available == true%>
        <li>
          <div class="columns">
            <%= link_to order_items_show_path( :item => "#{item.name}") do %>
              <div class="panel button", style="width:450px">
                <div class="left">
                <% unless item.img.to_s.nil? %>
                  <%= image_tag item.img, width:"150px" %>
                <% else %>
                  <%= image_tag("placeholder.png", width: "150px") %>
                <% end %>
                </div>
                <%= item.name%>
                <br><br>
                <%= item.description %>
                <br><br>
                <%= number_to_currency(item.price) %>
              </div>
            <% end %>
          </div>
        </li>
      <% end %>
    <% end %>
    </ul>
  </div>
<% elsif ["kids"].include? params[:view] %>
    <%= render 'kids_menu' %>
<% elsif ["Games"].include? params[:view] %>
  <p style="font-size:48px">
    <center><strong>Which game would you like to play?</strong></center>
  </p>
  <center><%= render 'games' %></center>
<%else %>
  <div>
  <p style="font-size:48px" class="centered large-offset-2" >
    <strong> What would you like to get started with?</strong>
    <br>
    We would recommend one of the following
  </p>
    <div class="rows">
      <div class="large-offset-4 columns centered">
        <div>
        <%= link_to "Drinks", guest_url(:view => "Drinks"), :method => "get", class: "large button radius" %>
        <%= link_to "Appetizers", guest_url(:view => "Appetizers"), :method => "get", class: "large button radius" %>
      </div>
    </div>
  </div>
<% end %>

app/views/user/_pay.html.erb
<fieldset class='small-8 small-centered text-center columns' style="width:500px;">
  <legend>Bill</legend>
  <% @items.each do |orderItem| %>
    <div class='panel'>
      <h4><%=(Menuitem.find(orderItem.item)).name%>: $<%=(Menuitem.find(orderItem.item)).price%></h4>
      <% user = User.find_by(username: session[:username]) %>
      <% unless orderItem.compitem.nil? %>
        <h4 style="color:#1F7A1F">Comp Value: <%= number_to_currency(orderItem.compitem.amount) %></h4>
      <% end %>
      <% if session[:accesslevel] > 2 %>
      <hr>
        <%= form_tag order_items_comp_path, :method => 'get' do %>
        <label>Comp Item Value
          <%= text_field_tag :comp_value, params[:comp_value], placehoder: "comp item"%>
        </label>
        <label>Reason
          <%= text_field_tag :reason, params[:reason], placehoder: "reason"%>
        </label>
        <%= hidden_field_tag :item_id, orderItem.item%>
        <%= hidden_field_tag :user, session[:username]%>
        <br>
        <%= submit_tag "Comp Item", class:"button success" %>
        <%end end%>
    </div>
  <% end %> 
  <hr>
  <% unless session[:ticket].nil?
  ticket = Ticket.where(table: session[:table_id]).last
			if ticket.birthday %>
				<h4 style="color:blue">Birthday discount: $10.00 off </h4>
			<% end
			if ticket.coupon %>
				<h4 style="color:blue">Coupon: $10.00 off </h4>
			<% end
			if ticket.points %>
				<h4 style="color:blue">Reward points: $10.00 off </h4>
			<% end %>
		<% end %>  

    <!-- Display value removed from ticket view compticket if it exists -->
    <% unless ticket.compticket.nil? %>
    <h4 style="color:#1F7A1F">Comp Value: <%= number_to_currency(ticket.compticket.amount) %></h4>
      <% end %>
    <h4 style="color:grey">Subtotal: <%= number_to_currency(@check.subtotal) %></h4>
    <h4 style="color:#FF6161">Tax: <%= number_to_currency(@check.tax) %></h4>
    <h4 style="color:#1C68FF">Gratuity: <%=number_to_currency(@check.gratuity)%></h4>
    
    <div class="row">
    <%= form_tag ticket_update_gratuity_path, :method => 'get' do%>
    <form>
      <label>Gratuity
        <%= text_field_tag :gratuity, params[:gratuity], :required => true%>
      </label>
      <%= submit_tag "Add Gratuity", class:"button success"%>
    </form>
    <%end%>
    </div>
    <div class="row">
    <%= form_tag guest_confirm_order_path, :method => 'get' do%>
    <form>
      <label>Coupon Code
        <%= text_field_tag :code, params[:code] %>
      </label>
      <%= submit_tag "Check Code", class:"button success"%>
      <%end%>
      <% user = User.find_by(username: session[:username]) %>
      <% if session[:accesslevel] > 2 %>
      <hr>
        <%= form_tag ticket_compticket_path, :method => 'get' do %>
        <label>Comp Ticket Value
          <%= text_field_tag :comp_value, params[:comp_value], placehoder: "comp ticket"%>
        </label>
        <label>Reason
          <%= text_field_tag :reason, params[:reason], placeholder: "reason" %>
        </label>
        <%= hidden_field_tag :ticket_id, session[:ticket]%>
        <%= hidden_field_tag :user, session[:username]%>
        <br>
        <%= submit_tag "Comp Ticket", class:"button success" %>
        <%end%>
    </form>
    <%end%>
    </div>    
    
    <h3 style="color:#1F7A1F">Total: <%= number_to_currency(@check.total) %></h3>
    <br>
    
    <!--Need to add a way to notify waiter -->
    <% if session[:accesslevel] > 2 %>
      <%= render 'calc_cash', :total => number_to_currency(@check.total)%>
      <%= link_to "Pay with Cash", guest_submit_payment_path, :method => "get", class: "button radius" %>
    <% else %>
      <%= link_to "Pay with Cash", waiter_help_path(:table => session[:table_id], :paying_cash => true), :data => {:confirm => 'a staff member has been notified to assist you'}, :method => "get", class: "button radius" %>
      <!-- Need to show credit partial -->
      <%= link_to "Pay with Credit", guest_pay_w_credit_path, class:"button radius" %>
    <% end %>

app/views/user/_waiter_button.html.erb
<!-- need to add way to show waiter ID so it looks like Waiter: "waiter ID"-->
<%= button_to "Waiter: ", root_url, :method => "get", class: "button round" %>

app/views/user/confirm_order.html.erb
<%= render 'top_nav_bar', view:'menu' %>
<%= render 'side_nav', view:'menu' %>
<script type="text/javascript">
  $(document).foundation();
</script>
<!-- If no ticket exists -->
<% if @check.nil? %>
  <center><h1>Choose an item to build a ticket.</h1></center>

  <!-- If ticket has not been sent to kitchen -->
<% elsif @check.tstatus == 0 %> 

<fieldset class='small-8 small-centered text-center columns'>
  <legend>Current Order</legend>

  <!-- loop through each item in order -->
  <% @items.each do |orderItem| %>
    <div class='panel'>
      <h4><%=(Menuitem.find(orderItem.item)).name%>: <%=number_to_currency((Menuitem.find(orderItem.item)).price)%></h4>
      Notes: <%= orderItem.notes %><br>
      <%= link_to 'Remove', order_items_remove_item_path(item_id: orderItem.item) %><br>
      
      <!-- show comp item ability if user is a server or manager -->
      <% user = User.find_by(username: session[:username]) %>
      <% if session[:accesslevel] > 2 %>
      <hr>
        <%= form_tag order_items_comp_path, :method => 'get' do %>
        <label>Comp Value
          <%= text_field_tag :comp_value, params[:comp_value], placehoder: "comp item"%>
        </label>
        <label>Reason
          <%= text_field_tag :reason, params[:reason], placehoder: "reason"%>
        </label>
        <%= hidden_field_tag :item_id, orderItem.item%>
        <%= hidden_field_tag :user, session[:username]%>
        <br>
        <%= submit_tag "Comp Item", class:"button success" %>
        <%end%>
      <%end%>
    </div>
 <% end %>
  
  <!-- TOTALS -->
  Subtotal: <%= number_to_currency(@check.subtotal) %><br>
  Tax: <%= number_to_currency(@check.tax) %><br>
  Total: <%= number_to_currency(@check.total) %><br>
  <hr>
  <p style="font-size:16px">You can choose to make your order To-Go after submitting your order.</p>

  <a href="" data-reveal-id="firstModal" class="radius button">Submit Order</a>
    
    <div id="firstModal" class="reveal-modal" data-reveal aria-labelledby="firstModalTitle" aria-hidden="true" role="dialog">
      <h2 id="firstModalTitle">Are you sure you want to submit?</h2>
      <p>Once you submit your order, you won't be able to edit it.</p>
      
      <%= form_tag ticket_advance_ticket_path, :method => 'get' do %>
        <p>Make your order To-Go <%=check_box_tag :togo%></p>
        <%= submit_tag "Yes", class:'button success center'%>
      <%end%>

      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>
   <!-- end of form_tag -->

  </fieldset>

  <!-- If ticket sent to kitchen but not out of kitchen -->
  <% elsif @check.tstatus == 1%>
    <div style="text-align:center">
      <h1 style="padding-top:64px;">Your food is in the kitchen</h1>
      <h3 style="color:grey;">Play the coupon game for a chance to earn a discount on your next meal!</h3>
      <br>

      <% #check params for code sent to validate code
      coupon = Coupon.find_by(code: params[:code])
      if coupon
        if coupon.usable && coupon.expiration >= Date.today
          @check.update(:coupon => true)
        else
          @check.update(:coupon => false)
          %>
          <% end end %>


      <a href="#" data-reveal-id="secondModal" class="radius button">Coupon Game</a>
      <div id="secondModal" class="reveal-modal" data-reveal aria-labelledby="secondModalTitle" aria-hidden="true" >
        <%= render 'couponGame' %>
      </div>
    </div>
    <div>
      <%= render 'pay' %>
    </div>

    <!-- If ticket out of kitchen but unpaid -->
  <% elsif @check.tstatus == 2%>
    <div style="text-align:center">
      <h1 style="padding-top:64px;">Your food is ready!</h1>
      <h3 style="color:grey;">Feel free to pay at anytime.</h3>
    </div>
    <div>
      <%= render 'pay' %>
    </div>        
  <% elsif @check.tstatus == 9 && session[:accesslevel] == 1 && session[:survey] == false %>
    <%=render 'survey' %>  
  <%end%>

app/views/user/kitchen.html.erb
<%= render 'top_nav_bar', :view => "kitchen" %>
<div class="coulmns large-10 right"><%= render 'tickets'%></div>
<%= render 'side_nav', :view => "kitchen" %>
<% if params[:view] == 'manager' %>
	<%=link_to "<< back to manager view", manager_path, :method => "get", class:"button info" %>
<% end %>

app/views/user/login.html.erb
<!-- Alert message -->
<div class="row">
  <div class="small3 small-centered text-center columns">
    <p id="alert">
     <font color="red"> <strong><%= alert %></strong></font>
    </p>
  </div>
</div>

<!-- login form -->
<div class="row">
  <div class="small-6 small-centered text-center columns">
    <%= form_tag login_path, :method => 'get' do %>
      <fieldset>
        <legend>Login</legend>
        <div class="row">
          <div class="small-12 columns">
            <%= text_field_tag :username, params[:username], placeholder: "Username" %>
            <div class="row">
              <div class="small-8 columns">
                <%= text_field_tag :password, params[:password], placeholder: "Password" %>
              </div>
              <div class="small-4 columns">
                <%= submit_tag "Submit", class: "button radius postfix"%>
              </div>
            </div>
          </div>
		 </div>
	  </fieldset>
    <% end %>
  </div>
</div>

app/views/user/refill.html.erb
<%= render 'top_nav_bar', view:'menu' %>
<div class='columns large-10 right'>
  <fieldset>
    <legend>Which drink would you like a refill for?</legend>
    <ul class='small-block-grid-3'>
      <% @items.each do |item| %>
        <li>
          <% menuitem = Menuitem.where(:id => item.item).first %>
          <% if menuitem.category == 'Drinks' %>
            <!-- Change root_url to path for the method to notify the waiter -->
            <%= link_to waiter_refills_path(:table => session[:table_id], :drink => menuitem.name) do %>
              <div class='panel button'>
              <% unless menuitem.img.to_s.nil? %>
                <%= image_tag menuitem.img, width:"150px" %>
              <% else %>
                <%= image_tag("placeholder.png", width: "150px") %>
               <% end %>
              <%= menuitem.name %> 
              </div>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </fieldset>
</div>
<%= render 'side_nav',view:'menu' %>

app/views/user/waiter.html.erb
<style>
div.columns large-10 right"{
	padding-left: 2cm;
}

.reveal-modal{
    position: fixed;
}

</style>
<center><%= render 'top_nav_bar', :view => "waiter" %></center>

<!-- Removed due to not working or required.
<div class="rows">
  <div class="large-2 columns" style="background:#333">
    <ul class = side-nav>
    <!--Modal to assign Server to Table--
    <a href="#" class="button radius" data-reveal-id="serverModal">Assign Servers</a>
    <div id="serverModal" class="reveal-modal full" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
      <h3 id="modalTitle">Assign Servers</h2>
      <!--Generating Tables--
      <div class="coulmns large-10 right">
      <div class="columns">
      <ul class="large-block-grid-4">
  
      <% tables = Table.all.where(:accesslevel => 1) %>
      <% tables.each do |tables|%>
  
      <li>
      <!--Generating each table to Assign--
        <a href="#" class="button split"><%="#{tables.username}"%> <span data-dropdown="drop"></span></a><br>
        <ul id="drop" class="f-dropdown" data-dropdown-content>
          <li><a href="#">Server1</a></li>
          <li><a href="#">Server2</a></li>
          <li><a href="#">Server3</a></li>
          <li><a href="#">Server4</a></li>
          <li><a href="#">Server5</a></li>
        </ul>

      </li>
  
      <%end%>
      </ul>
      </div>
      </div>
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>
    <!--End of Assign Servers--

    <% servers = User.all.where(:accesslevel => 3) %>
    <% servers.each do |servers|%>
    <li><%= button_to "#{servers.username}", tableview_path, :view => "Servers", :method => "get", class: "button success radius" %></li>
    <% end %>
    
	</ul>
  </div>
</div>
-->
<br>
<br>
<br>
<br>
<center>
<div class="coulmns large-10 right">
<div class="columns">
<ul class="large-block-grid-4">
  <% tables = Table.all.where(:accesslevel => 1) %>
  <% tables.each do |tables|%>
  <li>

    <%= link_to user_waiter_table_gateway_path(table_id: tables.username.byteslice(5,2)) do %>
  	<div id=<%="#{tables.username}"%> class="table panel button">
      <h2 id="modalTitle"><%="#{tables.username}"%></h2>
		<p>Status:  <!-- Get Table status -->
		<%= table = Ticket.find_by(table: tables.username.byteslice(5,2))
			unless table.nil?
				if table.tstatus == 0
					"Reading Menu"
				elsif table.tstatus == 1
					"Placed order and waiting on food"
				elsif table.tstatus == 2
					"Eating"
				elsif table.tstatus == 9
					"Paid"
				else
					"Unknown"
				end
			else
				"Open"
			end
				%></p><!--find ticket for table if one exists and get status -->
				<p>Refill: <%= tables.refills %></p>
				<br>
				
				<% if tables.help %>
					<p>***HELP REQUESTED***</p>
						 <%end	%>
					 <%=  link_to table_reset_status_path(:table => tables.username.byteslice(5,2)) do %>
								  <div class="button success radius">
								  Reset
								  </div>
								  <%end %>
    </div>
    <% end %>

  </li>
  <%end%>
</ul>
</div>
</div>
</center>